# Generated by Django 5.1.7 on 2025-03-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
